language: ruby

rvm:
  - 2.1

script: bundle exec jekyll build && bundle exec htmlproof ./_site

branches:
  only:
  - lax.github.io-github-pages
  - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
