# Site settings
title: 刘兰涛的技术博客
subtitle: "Idea, Code, Life"
email: liulantao (at) gmail.com
description: "Idea, Code, Life 思考的点点滴滴"
baseurl: ""
url: http://blog.liulantao.com
twitter_username: liulantao
github_username: Lax

author:
  name: Liu Lantao

comment_uyan_uid: 1936498

# Build settings
markdown: kramdown
permalink: pretty

permalink: /blog/:year/:year-:month-:day-:title.html
rss_path: /rss.xml
atom_path: /atom.xml
feed_path: /feed.xml
