# Site settings
title: 刘兰涛的技术博客
subtitle: blog.liulantao.com
email: liulantao (at) gmail.com
description: "Idea, Code, Life 思考的点点滴滴"
baseurl: ""
url: http://blog.liulantao.com

author:
  name: Liu Lantao
github_user: Lax
twitter_user: liulantao

comment_uyan_uid: 1936498
google_analytics_tracking_id: UA-1658815-1

# Build settings
markdown: kramdown
permalink: pretty

permalink: /blog/:year/:year-:month-:day-:title.html
rss_path: /rss.xml
atom_path: /atom.xml
feed_path: /feed.xml

releated_posts_limit: 3

exclude: [Rakefile, Gemfile, Gemfile.lock]

gems:
  - jekyll-sitemap
