# Site settings
title: 刘兰涛的技术博客
email: liulantao (at) gmail.com
description: "Idea, Code, Life 思考的点点滴滴"
baseurl: ""
url: http://blog.liulantao.com

github_user: Lax
twitter_user: liulantao

comment_uyan_uid: 1936498

# Build settings
markdown: kramdown
permalink: pretty

permalink: /blog/:year/:year-:month-:day-:title.html
