# Site settings
title: 刘兰涛的技术博客
email: liulantao (at) gmail.com
description: "Idea, Code, Life 思考的点点滴滴"
baseurl: ""
url: http://blog.liulantao.com
twitter_username: liulantao
github_username: Lax

# Build settings
markdown: kramdown
permalink: pretty

permalink: /blog/:year/:year-:month-:day-:title.html
